services:

  pgadmin:
    image: fenglc/pgadmin4
    environment:
#      PGADMIN_DEFAULT_EMAIL: user@domain.com
#      PGADMIN_DEFAULT_PASSWORD: 123
      SERVER_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - db_network
    restart: always
    tty: true
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:12-alpine
    shm_size: '512m'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: dataquality
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command:
      -c checkpoint_completion_target=0.9
      -c work_mem=96MB
#      -c wal_writer_delay=20ms
#      -c synchronous_commit=off
#      -c wal_buffers=32MB
#      -c min_wal_size=2GB
#      -c max_wal_size=4GB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 120s
      retries: 10
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge

volumes:
#  pgadmin:
  postgres:
